// <auto-generated />
using System;
using AritmaEnvanter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AritmaEnvanter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319094224_AddIslemYapanKisiToDepoStok")]
    partial class AddIslemYapanKisiToDepoStok
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.ArizaFormu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArizaTanimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("ArizaFormlari");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.AssetTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("EskiLokasyonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IslemTipi")
                        .HasColumnType("text");

                    b.Property<string>("IslemYapanKullaniciId")
                        .HasColumnType("text");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.Property<int?>("YeniLokasyonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IslemYapanKullaniciId");

                    b.ToTable("AssetTransactions");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Bakim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonrakiBakimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("UrunId");

                    b.ToTable("Bakimlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UstBirimId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UstBirimId");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Depo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("UstDepoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("UstDepoId");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.DepoHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HedefDepoId")
                        .HasColumnType("integer");

                    b.Property<int>("KaynakDepoId")
                        .HasColumnType("integer");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<string>("RafNo")
                        .HasColumnType("text");

                    b.Property<int?>("RafTanimId")
                        .HasColumnType("integer");

                    b.Property<int?>("TamirAtasmanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("RafTanimId");

                    b.HasIndex("TamirAtasmanId");

                    b.ToTable("DepoHareketler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.DepoStok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Birim")
                        .HasColumnType("text");

                    b.Property<int>("DepoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IslemYapanKisi")
                        .HasColumnType("text");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<string>("RafNo")
                        .HasColumnType("text");

                    b.Property<int?>("RafTanimId")
                        .HasColumnType("integer");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepoId");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("RafTanimId");

                    b.ToTable("DepoStoklar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormAlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlanTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FormSablonId")
                        .HasColumnType("integer");

                    b.Property<bool>("Gerekli")
                        .HasColumnType("boolean");

                    b.Property<string>("Secenekler")
                        .HasColumnType("text");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormSablonId");

                    b.ToTable("FormAlanlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barkod")
                        .HasColumnType("text");

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepoId")
                        .HasColumnType("integer");

                    b.Property<int>("FormSablonId")
                        .HasColumnType("integer");

                    b.Property<string>("KaydedenKullanici")
                        .HasColumnType("text");

                    b.Property<string>("KayitNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("DepoId");

                    b.HasIndex("FormSablonId");

                    b.ToTable("FormKayitlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormKayitDeger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deger")
                        .HasColumnType("text");

                    b.Property<int>("FormAlanId")
                        .HasColumnType("integer");

                    b.Property<int>("FormKayitId")
                        .HasColumnType("integer");

                    b.Property<string>("GorselUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormAlanId");

                    b.HasIndex("FormKayitId");

                    b.ToTable("FormKayitDegerler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormSablon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HiyerarsikId")
                        .HasColumnType("text");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UstFormId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("UstFormId");

                    b.ToTable("FormSablonlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HiyerarsikId")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UstKategoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Lokasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("Kat")
                        .HasColumnType("text");

                    b.Property<string>("OdaNo")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("ParentId");

                    b.ToTable("Lokasyonlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Malzeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlternatifAd")
                        .HasColumnType("text");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .HasColumnType("text");

                    b.Property<int?>("FormSablonId")
                        .HasColumnType("integer");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<string>("MalzemeTuru")
                        .HasColumnType("text");

                    b.Property<decimal?>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Raf")
                        .HasColumnType("text");

                    b.Property<int?>("RafId")
                        .HasColumnType("integer");

                    b.Property<string>("SeriNo")
                        .HasColumnType("text");

                    b.Property<string>("UrunTuru")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("FormSablonId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Malzemeler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.RafTanim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FizikselKonum")
                        .HasColumnType("text");

                    b.Property<string>("Iletisim")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SorumluPersonel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RafTanimlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.SatinAlma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("SatinAlmalar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.TamirAtasman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TamirAtasmanlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("HedefBirimId")
                        .HasColumnType("integer");

                    b.Property<int>("KaynakBirimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransferTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HedefBirimId");

                    b.HasIndex("KaynakBirimId");

                    b.HasIndex("UrunId");

                    b.ToTable("Transferler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.TransferTalep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HedefDepoId")
                        .HasColumnType("integer");

                    b.Property<int?>("KaynakDepoId")
                        .HasColumnType("integer");

                    b.Property<string>("OnaylayanUserId")
                        .HasColumnType("text");

                    b.Property<string>("TalepEdenUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HedefDepoId");

                    b.HasIndex("KaynakDepoId");

                    b.HasIndex("OnaylayanUserId");

                    b.HasIndex("TalepEdenUserId");

                    b.ToTable("TransferTalepler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("DepoId")
                        .HasColumnType("integer");

                    b.Property<string>("Durum")
                        .HasColumnType("text");

                    b.Property<string>("DynamicProperties")
                        .HasColumnType("jsonb");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("integer");

                    b.Property<int?>("LokasyonId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Miktar")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriNo")
                        .HasColumnType("text");

                    b.Property<string>("UrunTuru")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LokasyonId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Zimmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int?>("UrunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ZimmetTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UrunId");

                    b.ToTable("Zimmetler");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.ArizaFormu", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.AssetTransaction", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", "IslemYapanKullanici")
                        .WithMany()
                        .HasForeignKey("IslemYapanKullaniciId");

                    b.Navigation("IslemYapanKullanici");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Bakim", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId");

                    b.HasOne("AritmaEnvanter.Models.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Birim", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "UstBirim")
                        .WithMany("AltBirimler")
                        .HasForeignKey("UstBirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstBirim");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Depo", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "UstDepo")
                        .WithMany("AltDepolar")
                        .HasForeignKey("UstDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Birim");

                    b.Navigation("UstDepo");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.DepoHareket", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "HedefDepo")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "KaynakDepo")
                        .WithMany()
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.RafTanim", "RafTanim")
                        .WithMany()
                        .HasForeignKey("RafTanimId");

                    b.HasOne("AritmaEnvanter.Models.Entities.TamirAtasman", "TamirAtasman")
                        .WithMany("Hareketler")
                        .HasForeignKey("TamirAtasmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HedefDepo");

                    b.Navigation("KaynakDepo");

                    b.Navigation("Malzeme");

                    b.Navigation("RafTanim");

                    b.Navigation("TamirAtasman");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.DepoStok", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.RafTanim", "RafTanim")
                        .WithMany()
                        .HasForeignKey("RafTanimId");

                    b.Navigation("Depo");

                    b.Navigation("Malzeme");

                    b.Navigation("RafTanim");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormAlan", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.FormSablon", "FormSablon")
                        .WithMany("Alanlar")
                        .HasForeignKey("FormSablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormSablon");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormKayit", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId");

                    b.HasOne("AritmaEnvanter.Models.Entities.FormSablon", "FormSablon")
                        .WithMany("Kayitlar")
                        .HasForeignKey("FormSablonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Depo");

                    b.Navigation("FormSablon");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormKayitDeger", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.FormAlan", "FormAlan")
                        .WithMany()
                        .HasForeignKey("FormAlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.FormKayit", "FormKayit")
                        .WithMany("Degerler")
                        .HasForeignKey("FormKayitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormAlan");

                    b.Navigation("FormKayit");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormSablon", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.HasOne("AritmaEnvanter.Models.Entities.FormSablon", "UstForm")
                        .WithMany("AltFormlar")
                        .HasForeignKey("UstFormId");

                    b.Navigation("Kategori");

                    b.Navigation("UstForm");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Kategori", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Lokasyon", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("AritmaEnvanter.Models.Entities.Lokasyon", "ParentLokasyon")
                        .WithMany("AltLokasyonlar")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Birim");

                    b.Navigation("ParentLokasyon");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Malzeme", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("AritmaEnvanter.Models.Entities.FormSablon", "FormSablon")
                        .WithMany()
                        .HasForeignKey("FormSablonId");

                    b.HasOne("AritmaEnvanter.Models.Entities.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("Birim");

                    b.Navigation("FormSablon");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Personel", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.SatinAlma", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Transfer", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "HedefBirim")
                        .WithMany()
                        .HasForeignKey("HedefBirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "KaynakBirim")
                        .WithMany()
                        .HasForeignKey("KaynakBirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HedefBirim");

                    b.Navigation("KaynakBirim");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.TransferTalep", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "HedefDepo")
                        .WithMany()
                        .HasForeignKey("HedefDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AritmaEnvanter.Models.Entities.Depo", "KaynakDepo")
                        .WithMany()
                        .HasForeignKey("KaynakDepoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", "OnaylayanUser")
                        .WithMany()
                        .HasForeignKey("OnaylayanUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", "TalepEdenUser")
                        .WithMany()
                        .HasForeignKey("TalepEdenUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HedefDepo");

                    b.Navigation("KaynakDepo");

                    b.Navigation("OnaylayanUser");

                    b.Navigation("TalepEdenUser");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Urun", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Birim", "Birim")
                        .WithMany("Urunler")
                        .HasForeignKey("BirimId");

                    b.HasOne("AritmaEnvanter.Models.Entities.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.HasOne("AritmaEnvanter.Models.Entities.Lokasyon", "Lokasyon")
                        .WithMany()
                        .HasForeignKey("LokasyonId");

                    b.Navigation("Birim");

                    b.Navigation("Kategori");

                    b.Navigation("Lokasyon");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Zimmet", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.Malzeme", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Personel", "Personel")
                        .WithMany("Zimmetler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId");

                    b.Navigation("Malzeme");

                    b.Navigation("Personel");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AritmaEnvanter.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Birim", b =>
                {
                    b.Navigation("AltBirimler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Depo", b =>
                {
                    b.Navigation("AltDepolar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormKayit", b =>
                {
                    b.Navigation("Degerler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.FormSablon", b =>
                {
                    b.Navigation("Alanlar");

                    b.Navigation("AltFormlar");

                    b.Navigation("Kayitlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Lokasyon", b =>
                {
                    b.Navigation("AltLokasyonlar");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.Personel", b =>
                {
                    b.Navigation("Zimmetler");
                });

            modelBuilder.Entity("AritmaEnvanter.Models.Entities.TamirAtasman", b =>
                {
                    b.Navigation("Hareketler");
                });
#pragma warning restore 612, 618
        }
    }
}

